spring.application.name=System_Food_Truck

#Conexao com o PostGreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/foodtruck_db
spring.datasource.username=postgres
spring.datasource.password=PI29
spring.datasource.driver-class-name=org.postgresql.Driver

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

